name: Terraform deployment
on:
 workflow_call:
  inputs:
   subscriptionId:
    type: string
    description: Subscrition ID to use for deployment
    required: false
   runnerName:
    type: string
    description: Runner to use for deployment
    required: false
    default: 'ubuntu-latest'
   workingDirectory:
    type: string
    description: 'The working directory for Terraform commands'
    required: true

jobs:
 Deployment:
  runs-on: ${{inputs.runnerName}}
  env:
    AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
  defaults:
   run:
    working-directory: ${{inputs.workingDirectory}}
  steps:
   - name: Checkout Code
     uses: actions/checkout@v6
   - name: Az login
     run: az login --username "mohammednizamuddin@snp.com" --password "$AZURE_PASSWORD" --tenant 30bf9f37-d550-4878-9494-1041656caf27        

   - name: Setup Terraform
     uses: hashicorp/setup-terraform@v3

   - name: Terraform init
     run: terraform init

   - name: Terraform plan
     run: terraform plan -out=tfplan


